### ISSUE TITLE
Versioned release

### ISSUE THREAD

**Issue by absolutelynothinghere** [raygard/wak#7]
Are there plans to make a versioned (numbered) release of wak?

Thank you.

**Comment by raygard** [comment]
I had not thought about that yet. Do you think it is mature enough for that yet? Are you using it?

**Comment by absolutelynothinghere** [comment]
>Are you using it?

It seems to satisfy autotools so I suppose yes, but I haven't tested wak beyond that. The [busybox test suite](https://github.com/akretion/busybox-remastering/blob/master/testsuite/awk.tests) might come in handy.

>Do you think it is mature enough for that yet?

Only you can decide when it is ready, I was simply making a suggestion for the future.

**Comment by davidar** [comment]
I'm also using it to keep various build scripts (including autotools) happy. It works quite well with [tcc](https://bellard.org/tcc/) too, I've just been putting

```sh
#!/usr/local/bin/tcc -run
```

at the top of the monolithic source file and running it like a script

**Comment by iriswebb** [comment]
> I'm also using it to keep various build scripts (including autotools) happy. It works quite well with [tcc](https://bellard.org/tcc/) too, I've just been putting
> 
> ```shell
> #!/usr/local/bin/tcc -run
> ```
> 
> at the top of the monolithic source file and running it like a script

If you don't mind sharing, what environment (libc version, tcc version,
operating system) are you running? I took a shot at running it like a
script and got a error:

```
$ ./monosrc/mono.c
In file included from ./monosrc/mono.c:24:
/usr/include/regex.h:682: error: '__nmatch' undeclared
```

That line of /usr/include/regex.h on my system (glibc 2.39-2 (x86_64) on Arch Linux) is:
```c
extern int regexec (const regex_t *_Restrict_ __preg,
        const char *_Restrict_ __String, size_t __nmatch,
        regmatch_t __pmatch[_Restrict_arr_
          _REGEX_NELTS (__nmatch)],
         int __eflags);
```

Which evaluates to (when removing the irrelevant "const" and "restrict" stuff):
```c
extern int regexec (regex_t *__preg, char *__String, size_t __nmatch, regmatch_t __pmatch[__nmatch], int __eflags)
```

The problem seems to be:
```
$ tcc -run -
extern int a(int b, char c[b]);
<stdin>:1: error: 'b' undeclared
```

Pointing it at my musl headers gives a different error in a typecast for bits/alltypes.h

My version of tcc might also just be old and someone patched in support for this
in a different version. Don't know

**Comment by davidar** [comment]
I'm using a recent build of the mob branch of https://repo.or.cz/w/tinycc.git. I've used glibc 2.35 on ubuntu 22.04, as well as my own fork of musl (https://github.com/davidar/musl/tree/tcc) which just has a handful of changes allowing musl itself to be built with tcc. If you're using a versioned release of tcc then it's probably missing quite a lot of changes as the last one was 6 years ago.

```
$ tcc -v
tcc version 0.9.28rc 2024-04-09 mob@6b3cfdd0 (x86_64 Linux)
$ tcc -run -
extern int a(int b, char c[b]);
main(){puts("ok!");}
-:1: warning: implicit declaration of function 'puts'
ok!
```

**Comment by iriswebb** [comment]
> I'm using a recent build of the mob branch of https://repo.or.cz/w/tinycc.git.

I didn't know tcc was still being updated. Thanks!

My version of tcc was "tcc version 0.9.27 (x86_64 Linux)" which has a 2000-2006 Copyright notice (It's The latest version the Arch repos provide).

Using the version you provide, I'm not just able to compile wak, but with some minimal changes (`#define QUIET` in lib/portability.h (Because it only adds it if it's using gcc) and removing the LDOPTIMIZE flags tcc doesn't have) compile the toybox 5.5x faster than with gcc (28s -> 5s). Along with stuff like mksh, nawk, sbase, and many other programs.

Like I said, thanks!

**Comment by davidar** [comment]
@oliverkwebb No worries! I've been using tcc (and wak) for https://github.com/davidar/bootsh, it's quite impressive how much software can be compiled with it these days, and indeed it is quite fast. Having the one-file implementation of wak has been quite useful for bootstrapping it separately without bloating the main bootsh binary, so I hope that wak will remain a standalone project in addition to the option of integrating it with toybox. It's been quite indispensable too, given that so many C build systems rely on awk in one way or another, so thanks for your work on this compact and portable implementation :)

**Comment by raygard** [comment]
@davidar David, you're welcome! I'm glad someone is using wak to good purpose. Took a while to write it (understatement there), and I don't know if it will be accepted into toybox; I wrote it sort of on spec. Let me know if you find bugs (it has some for sure) or have ideas for enhancements. Trying to keep it small, but will consider it. I do intend to fix any real bugs but will probably not be doing much more unless/until Rob Landley gets it into toybox.

I tried tcc and it's amazingly fast; execution a bit slow but that's OK for what I'd want it for. Questions: I tried the `#!/usr/local/bin/tcc -run` to run it as a script and that worked fine. When I tried compiling, it didn't find the math functions until I added `-lm` to the `tcc mono.c` command line. Why does the `-run` thing work without `-lm`?

**Comment by davidar** [comment]
@raygard Generally speaking it's been working pretty well, but one issue that I've run into is with "interactive" awk scripts. For instance:

```
$ mawk '/^say / { print $2 }'
say hello
hello
say goodbye
goodbye
^D
$ ./wak.c '/^say / { print $2 }'
say hello
say goodbye
^D
hello
goodbye
^D
```

It seems like it's not line-buffering the input, though I'm slightly confused why that is as, looking at the code, it seems like it should be (at least in `get_char`, not sure about `getrec_` functions). I can kind of get it to work by pressing ctrl-D after each line of input:

```
$ ./wak.c '/^say / { print $2 }'
say hello
^D
hello
say goodbye
^D
goodbye
^D
```

mawk behaves similarly in some circumstances (https://github.com/ThomasDickey/original-mawk/issues/41#issuecomment-241070898) because they're block buffering input, is wak doing something similar?

**EDIT:** I figured out how to make this work (https://github.com/davidar/bootsh/commit/acee3572e83f4b008db0f7b3ab705b3306525101), I can submit a PR for it if you like

> Why does the -run thing work without -lm?

Good question, initially I assumed it was just automatically adding common libraries for convenience, but that doesn't appear to be the case. I think it's actually just because `-run` executes the program in the same process as `tcc`, which itself is already linked to libm, so it's visible without needing to explicitly load it.

**Comment by raygard** [comment]
@absolutelynothinghere, I have issued a versioned release, 24.8.

**Comment by raygard** [comment]
@davidar: I have addressed your problem with interactive input. Note that your fix was helpful but there was more to it. Simply using `fgets()` in place of `fread()` only works if `RS` is `<newline>` (`"\n"`), which is the default, but I've gone to some trouble to make `wak` work with arbitrary regex as `RS`. I have fixed up the code to use your `fgets()` approach only if input is a tty (`isatty()`) and `RS` is a newline.
Also, thank you muchly for the tip on using tcc, it's amazing! I am using your "script" trick and it's really nice to be able to tweak the code and run it immediately with no need for a separate compile. One thing though: some code requires the `char` type to be unsigned, and apparently tcc has it signed by default, so I have to use `#!/usr/local/bin/tcc -run -funsigned-char` in front of `mono.c`.

**Comment by iriswebb** [comment]
A additional note on compiler portability: I've also gotten the mono source code for wak to build under [cproc](https://git.sr.ht/~mcf/cproc), Which is essentially the dash of C compilers (ISO compliance over pragmatic use).

Since cproc has no `-f` options the source code has to be compiled with `cproc monosrc/mono.c` instead of `make mono CC=cproc`.

**Comment by raygard** [comment]
I have published v24.10 and am closing this issue. Thanks to all who contributed.

**Comment by rofl0r** [comment]
> One thing though: some code requires the char type to be unsigned, and apparently tcc has it signed by default, so I have to use #!/usr/local/bin/tcc -run -funsigned-char in front of mono.c.

pretty much all platforms except for ARM default to char == signed char. the same issue should be visible when you compile for linux x86_64 with e.g. gcc or clang. so for best portability it's recommendable to always write "unsigned char" if unsigned semantics are needed.

as an aside, i recently stumbled upon this article https://lorentz.app/blog-item.html?id=go-shebang which inspired me to come up with a sort of portable "run C as script" shebang that should work with any compiler in a fashion like this `//bin/gcc "$0" -o /dev/shm/shebang.$$.elf && /dev/shm/shebang.$$.elf "$@"; exit` . it could probably be made better by using /usr/bin/env to look up the compiler path and by removing temp files.

**Comment by raygard** [comment]
@rofl0r Thank you for this comment, that I almost missed! What led you to comment on this closed issue, which was not initially about anything like whether to assume char is unsigned? I mean how did you even come across it?

I initially wrote this awk implementation intending to get it into Rob Landley’s toybox project (now found at codeberg.org), and I tried hard to stick with his conventions on style and such. He assumes toybox will be compiled with char forced to unsigned, so I did the same. (At this point I’ve given up hope that it will ever be accepted into the built-by-default posix folder in toybox.)

But I have already done some work since what I have up on github, including a patch to remove the assumption that char is unsigned. Turns out that it only mattered in a few places and I can mask things as needed, but I want to test it more before updating. I am still getting up to speed on Linux and have been sidetracked with other projects but intend to get back to this “real soon now”.

Unrelated, but if you’re using this I’d appreciate your input: I am considering renaming the project to zawk. I was never happy with the name wak and wanted to call it zawk from the get-go but saw that there was already something called zawk at github and didn’t want to cause a conflict. But now I see that there are quite a few zawk repos out there so maybe one more will not really be a problem. Any thoughts on that?

I’ll take a look at your magic shebang, thanks.

**Comment by rofl0r** [comment]
> I mean how did you even come across it?

the mawk issue that's cross-linked to here was closed some days ago (after being open for years), so i was curious when i saw this topic linked there. davidar's bootstrapping method that was added to my distro sabotage linux a while ago uses wak.

>  I tried hard to stick with his conventions on style and such

ah, makes sense.

> I am considering renaming the project to zawk. I was never happy with the name wak and wanted to call it zawk from the get-go but saw that there was already something called zawk at github and didn’t want to cause a conflict. But now I see that there are quite a few zawk repos out there so maybe one more will not really be a problem. Any thoughts on that?

well, i see it the opposite way. if there are several zawk's then it will be hard to get noticed. since the name wak is already established/known and hopefully unique, i'd stick to it.

**Comment by raygard** [comment]
@rofl0r I guess I'll stick with the name wak. I have no idea how much use it's getting. Thanks for the input.

What is the mawk issue that's cross-linked to here? I can't find anythink likely at github.com/ThomasDickey/original-mawk . Where can I see what you're referring to?

Ahh never mind, I see it now -- mawk issue #41 @davidar mentioned above. Thanks.
