### ISSUE TITLE
Will wak get added to toybox?

### ISSUE THREAD

**Issue by firasuke** [raygard/wak#8]
Hey there, thank you for your time and effort.

wak looks very promising, will it be added to upstream toybox?

**Comment by raygard** [comment]
@firasuke, Thanks for noticing wak. It doesn't have much publicity. How did you discover it?

The toybox version of wak (wak/toybox/awk.c) was added to toybox late June or early July and updated Sep 3 to the almost-latest version. It's in toybox/toys/pending/awk.c with tests in toybox/tests/awk.test. I don't know when or if Rob will "promote" it to the toybox/toys/posix folder. For now, you need to use `make menuconfig` when building toybox and select awk in the pending menu. If it gets into the posix folder, it will be built into toybox by default. I hope to convince Rob to promote it soon, but we'll see how that goes.

BTW there's a little documentation on the development of it here: https://www.raygard.net/awkdoc/ . I don't think I have a link to that in the README.md file yet. I'll beef up the README soon, I hope. I have some valuable feedback from Nelson H. F. Beebe that I need to attend to, also.

**Comment by firasuke** [comment]
Oh, I checked version `0.8.11` and I noticed it wasn't there, so it was added later, interesting..

I was searching for possible alternatives to `mawk` and I found `wak`, the only concern I have is about its performance, could it be improved to be on par with `mawk`?

Thanks for your time and effort!

**Comment by raygard** [comment]
Toybox releases have been a bit irregular lately, Rob Landley has had some issues with moving to a different state and hassles with changing laptops I think.

I intend to try to improve its performance, but it may never get close to as fast as mawk. One of the main goals has been to keep wak as small as I reasonably can, as Rob would prefer. In fact, I believe he thinks it is already too big. It will be a challenge to significantly improve its performance while not making it much larger than it is. I tend to think of its performance more in comparison with busybox awk rather than other implementations, as toybox is intended, I think as a replacement for busybox. I think wak is already faster than busybox awk.

How did you find wak?

**Comment by firasuke** [comment]
> Toybox releases have been a bit irregular lately, Rob Landley has had some issues with moving to a different state and hassles with changing laptops I think.
> 
> I intend to try to improve its performance, but it may never get close to as fast as mawk. One of the main goals has been to keep wak as small as I reasonably can, as Rob would prefer. In fact, I believe he thinks it is already too big. It will be a challenge to significantly improve its performance while not making it much larger than it is. I tend to think of its performance more in comparison with busybox awk rather than other implementations, as toybox is intended, I think as a replacement for busybox. I think wak is already faster than busybox awk.
> 
> How did you find wak?

Oh interesting. I tried wak and it seems like a solid replacement for gawk/mawk. My only complaint is the performance, as currently it is 2-3 times slower than gawk, and up to 8-10 times slower compared to mawk which is a lot.

I have high hopes though, keep up the great work!

Closing..
